// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbkguz5uHU-rGatZvRKewRwO6wu3TICEk',
    appId: '1:1044631131672:web:22bc2fb4d4a0873499556d',
    messagingSenderId: '1044631131672',
    projectId: 'face-attendance-54ca5',
    authDomain: 'face-attendance-54ca5.firebaseapp.com',
    storageBucket: 'face-attendance-54ca5.firebasestorage.app',
    measurementId: 'G-HNJTW8QTL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWe3pJ3Ij7gc6LoflBYU00HkDUO1tFvE8',
    appId: '1:1044631131672:android:303432d0bf1c50dc99556d',
    messagingSenderId: '1044631131672',
    projectId: 'face-attendance-54ca5',
    storageBucket: 'face-attendance-54ca5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsT0rPs-6yqEFj3Iwx2vSOlRouuKSY--4',
    appId: '1:1044631131672:ios:ad1ff39afa23d5a999556d',
    messagingSenderId: '1044631131672',
    projectId: 'face-attendance-54ca5',
    storageBucket: 'face-attendance-54ca5.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsT0rPs-6yqEFj3Iwx2vSOlRouuKSY--4',
    appId: '1:1044631131672:ios:ad1ff39afa23d5a999556d',
    messagingSenderId: '1044631131672',
    projectId: 'face-attendance-54ca5',
    storageBucket: 'face-attendance-54ca5.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbkguz5uHU-rGatZvRKewRwO6wu3TICEk',
    appId: '1:1044631131672:web:f26bcaa9a7bc4b1d99556d',
    messagingSenderId: '1044631131672',
    projectId: 'face-attendance-54ca5',
    authDomain: 'face-attendance-54ca5.firebaseapp.com',
    storageBucket: 'face-attendance-54ca5.firebasestorage.app',
    measurementId: 'G-JSNNQC4N76',
  );
}
